name: Lambda GET build and push
permissions:
    id-token: write
    contents: write
on:
    push:
        branches:
            - main
        paths:
            - "lambda_containers/get/**"
    workflow_dispatch:
jobs:
    lambda_get_build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v6

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v5.1.0
              with:
                aws-region: eu-central-1
                role-to-assume: arn:aws:iam::299097238534:role/incident-logger-github-actions-ecr-role
                role-session-name: LambdaGETDeploySession

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag, and push image to Amazon ECR
              working-directory: lambda_containers/get
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: incident-logger-lambda-get-image-repository
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
                echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

            - name: Deploy to Lambda
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: incident-logger-lambda-image-repository
                IMAGE_TAG: ${{ github.sha }}
                LAMBDA_FUNCTION_NAME: incident-logger-lambda-get-incidents
              run: |
                aws lambda update-function-code \
                  --function-name $LAMBDA_FUNCTION_NAME \
                  --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

                echo "Waiting for Lambda function to update..."
                aws lambda wait function-updated \
                  --function-name $LAMBDA_FUNCTION_NAME

                echo "Lambda function updated successfully!"